name: pipeline pentrega evaluacion 1
on:
  push:

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v7
      - name: Verifica el contenido del repositorio
        run:
          echo "Este es el arbol del contenido del repositorio:"
          tree
      
      - name: Verificar Node
        run:
          node --version